### ISSUE TITLE
first_pass_api returns error

### ISSUE THREAD

**Issue by valearna** [WormBase/ACKnowledge#285]
@draciti This is related to the issue with 00065682 (authors submitted data but the form is blank). @azurebrd the first_pass_api.cgi form for this paper returns a blank page and I can see this error in the apache error log:

Uncaught exception from user code:
        Wide character at /usr/lib/pub/cgi-bin/forms/textpresso/first_pass_api.cgi line 72.
        main::jsonPaper(00065682) called at /usr/lib/pub/cgi-bin/forms/textpresso/first_pass_api.cgi line 52
        main::process() called at /usr/lib/pub/cgi-bin/forms/textpresso/first_pass_api.cgi line 46

Can you take a look at this @azurebrd ?

**Comment by azurebrd** [comment]
@draciti @valearna This was taking data from the database and decoding to utf-8 before passing it, and that's failing because of the Wide character in the database.   I don't know why we were decoding it, or what the output of this is used for.  I've stopped decoding it, and it doesn't fail anymore, but I don't know if that's going to cause other failures downstream.

**Comment by valearna** [comment]
Thanks @azurebrd, I've checked a few papers and everything seems to be fine now.

**Comment by azurebrd** [comment]
@valearna  great !

**Comment by draciti** [comment]
thanks @azurebrd and @valearna !
